export const SHOW_ALERT = 'ALERT-SHOW_ALERT'
export const HIDE_ALERT = 'ALERT-HIDE_ALERT'

export const SHOW_LOADER = 'FIREBASE-SHOW_LOADER'
export const ADD_TODO = 'FIREBASE-ADD_TODO'
export const FETCH_TODOS = 'FIREBASE-FETCH_TODOS'
export const REMOVE_TODO = 'FIREBASE-REMOVE_TODO'
export const SET_TODO_LIST = 'FIREBASE-SET_TODO_LIST'